### ISSUE TITLE
WHMCS 7 pagina en blanco

### ISSUE THREAD

**Issue by fabolivark** [epayco/Plugin_ePayco_WHMCS#1]
Forzando que muestre los errores whmcs aparece el siguiente Warning que deja la pantalla en blanco.

Warning: Cannot modify header information - headers already sent by (output started at /home/user_cpanel/public_html/modules/gateways/payco.php:143) in /home/user_cpanel/public_html/vendor/whmcs/whmcs-foundation/lib/Application.php on line 0

**Comment by epayco** [comment]
Hola @fabolivark  quiero comentarte que ya se encuentra actualizado WHMCS para la version 7.0.x
Puedes descargarlo directamente desde nuestro Github.
