### ISSUE TITLE
WHMCS 7.1 No funciona el Callback que actualiza el pago de factura

### ISSUE THREAD

**Issue by fabolivark** [epayco/Plugin_ePayco_WHMCS#3]
Cuando se realiza la compra en la version 6 se actualizaba el pago automaticamente y se renovaba el servicio, ahora en la version 7 recibe el pago en epayco pero en WHMCS no sucede nada.

**Comment by epayco** [comment]
Hola @fabolivark quiero comentarte que ya se encuentra actualizado WHMCS para la version 7.0.x
Puedes descargarlo directamente desde nuestro Github.
